AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-example-db — Rust Lambda with DynamoDB backend

Parameters:
  EnvironmentName:
    Type: String
    Default: Prod
    AllowedPattern: "^[A-Za-z0-9_-]+$"
    Description: Deployment environment name (e.g., Prod, Staging, Local)
  JwtSecretParameterPrefix:
    Type: String
    Default: /apps/aws-lambda-example-db
    Description: |
      Prefix for the JWT secret stored in SSM Parameter Store (include the leading `/`
      and avoid reserved segments like `aws`, `ssm`, or `amazon`).
      The deployed Lambda reads ${prefix}/${EnvironmentName}/JWT_SECRET.

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "Users_${EnvironmentName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: familyId
          AttributeType: S
        - AttributeName: userName
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: FamilyIdIndex
          KeySchema:
            - AttributeName: familyId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: FamilyUserIndex
          KeySchema:
            - AttributeName: familyId
              KeyType: HASH
            - AttributeName: userName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UserCredentialsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "UserCredentials_${EnvironmentName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  UserRefreshTokensTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "UserRefreshTokens_${EnvironmentName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: refreshToken
          AttributeType: S
        - AttributeName: familyId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: refreshToken
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: FamilyIdIndex
          KeySchema:
            - AttributeName: familyId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: FamilyUserIndex
          KeySchema:
            - AttributeName: familyId
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-lambda-example-db
      Handler: bootstrap
      CodeUri: ./target/lambda/aws-lambda-example-db
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName
          CREDENTIALS_TABLE_NAME: !Ref UserCredentialsTable
          REFRESH_TOKEN_TABLE_NAME: !Ref UserRefreshTokensTable
          JWT_SECRET_PARAMETER: !Sub "${JwtSecretParameterPrefix}/${EnvironmentName}/JWT_SECRET"
          AWS_LAMBDA_HTTP_IGNORE_STAGE_IN_PATH: "true"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserCredentialsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserRefreshTokensTable
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${JwtSecretParameterPrefix}/${EnvironmentName}/JWT_SECRET
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /users
            Method: ANY
        LoginApi:
          Type: Api
          Properties:
            Path: /login
            Method: POST
        TokenRefreshApi:
          Type: Api
          Properties:
            Path: /token/refresh
            Method: POST
        TokenRevokeApi:
          Type: Api
          Properties:
            Path: /token/revoke
            Method: POST

  UserDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${AWS::StackName}-lambda"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Invocations & Errors",
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${UserFunction}" ],
                  [ ".", "Errors", ".", "." ]
                ]
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "timeSeries",
                "region": "${AWS::Region}",
                "title": "Duration p50 / p95",
                "metrics": [
                  [ "AWS/Lambda", "Duration", "FunctionName", "${UserFunction}", { "stat": "p50" } ],
                  [ ".", ".", ".", ".", { "stat": "p95" } ]
                ]
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "timeSeries",
                "region": "${AWS::Region}",
                "title": "Throttles & Concurrent Execs",
                "metrics": [
                  [ "AWS/Lambda", "Throttles", "FunctionName", "${UserFunction}" ],
                  [ ".", "ConcurrentExecutions", ".", "." ]
                ]
              }
            },
            {
              "type": "log",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/${UserFunction}' | fields @timestamp, @message | sort @timestamp desc | limit 20",
                "region": "${AWS::Region}",
                "title": "Recent Lambda Logs"
              }
            }
          ]
        }

Outputs:
  UsersApiUrl:
    Description: Invoke URL for API Gateway stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users"
  TableName:
    Description: DynamoDB table name
    Value: !Ref UserTable
  CredentialsTableName:
    Description: DynamoDB credentials table name
    Value: !Ref UserCredentialsTable
  RefreshTokensTableName:
    Description: DynamoDB refresh token table name
    Value: !Ref UserRefreshTokensTable
