//! A derive macro: `#[derive(Describe)]`.
//!
//! For a struct with named fields it generates two methods:
//!   - `describe(&self) -> String`: "Name { field: value, … }", every field
//!     printed with `{:?}` (so every field type must implement Debug);
//!   - `field_names() -> &'static [&'static str]`: the field names, in order.
//!
//! A procedural macro is ordinary Rust code that runs INSIDE the compiler.
//! It receives the struct's source code as tokens, and returns new tokens
//! that the compiler adds to the program.

use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, parse_macro_input};

/// `#[proc_macro_derive(Describe)]` registers this function as the
/// implementation of `#[derive(Describe)]`.
#[proc_macro_derive(Describe)]
pub fn derive_describe(input: TokenStream) -> TokenStream {
    // 1. PARSE: turn the raw tokens into a syntax tree we can inspect.
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;

    // 2. INSPECT: we only support structs with named fields. For anything
    //    else, report a clear compile error pointing at the user's code.
    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return error(
                    &input,
                    "Describe needs a struct with named fields, like `struct S { a: u32 }`",
                );
            }
        },
        _ => {
            return error(
                &input,
                "Describe can only be derived for structs, not enums or unions",
            );
        }
    };

    let field_idents: Vec<_> = fields.iter().map(|f| f.ident.as_ref().unwrap()).collect();
    let field_names: Vec<String> = field_idents.iter().map(|i| i.to_string()).collect();

    // 3. GENERATE: `quote!` is a template. `#name` inserts a variable, and
    //    `#( … )*` repeats once per field, just like `$( … )*` in macro_rules!.
    let generics = &input.generics;
    let (impl_generics, type_generics, where_clause) = generics.split_for_impl();
    let expanded = quote! {
        impl #impl_generics #name #type_generics #where_clause {
            /// Generated by `#[derive(Describe)]`.
            pub fn describe(&self) -> String {
                let parts: Vec<String> = vec![
                    #( format!("{}: {:?}", #field_names, self.#field_idents) ),*
                ];
                format!("{} {{ {} }}", stringify!(#name), parts.join(", "))
            }

            /// Generated by `#[derive(Describe)]`.
            pub fn field_names() -> &'static [&'static str] {
                &[ #( #field_names ),* ]
            }
        }
    };

    // 4. RETURN the new code to the compiler.
    expanded.into()
}

/// Turns a message into a compile error at the location of `input`.
fn error(input: &DeriveInput, message: &str) -> TokenStream {
    syn::Error::new_spanned(&input.ident, message)
        .to_compile_error()
        .into()
}
